// Generated by kei_emit from greet.kei.
// Do not edit; regenerate with `kei build`.

export type Greeting = {
  readonly count: number;
};

export function Greeting(fields: Greeting): Greeting {
  return fields;
}

export function bump(g: Greeting): Greeting {
  return Greeting({ count: g.count + 1 });
}
//# sourceMappingURL=greet.ts.map
