// Generated by vow_emit from math.vow.
// Do not edit; regenerate with `vow build`.

import { VowContractViolation } from "@vow/runtime";

/**
 * requires a > 0
 * requires b > 0
 * ensures result == a + b
 */
export function addPositive(a: number, b: number): number {
  if (!(a > 0)) {
    throw new VowContractViolation({
      clause: "requires",
      func: "addPositive",
      condition: "a > 0",
      file: "math.vow",
      line: 4,
      col: 12,
    });
  }
  if (!(b > 0)) {
    throw new VowContractViolation({
      clause: "requires",
      func: "addPositive",
      condition: "b > 0",
      file: "math.vow",
      line: 5,
      col: 12,
    });
  }
  const vow$result = ((): number => {
    return a + b;
  })();
  if (!(vow$result === a + b)) {
    throw new VowContractViolation({
      clause: "ensures",
      func: "addPositive",
      condition: "result == a + b",
      file: "math.vow",
      line: 6,
      col: 11,
    });
  }
  return vow$result;
}
//# sourceMappingURL=math.ts.map
