// Generated by kei_emit from math.kei.
// Do not edit; regenerate with `kei build`.

import { KeiContractViolation } from "@kei/runtime";

/**
 * requires a > 0
 * requires b > 0
 * ensures result == a + b
 */
export function addPositive(a: number, b: number): number {
  if (!(a > 0)) {
    throw new KeiContractViolation({
      clause: "requires",
      func: "addPositive",
      condition: "a > 0",
      file: "math.kei",
      line: 4,
      col: 12,
    });
  }
  if (!(b > 0)) {
    throw new KeiContractViolation({
      clause: "requires",
      func: "addPositive",
      condition: "b > 0",
      file: "math.kei",
      line: 5,
      col: 12,
    });
  }
  const kei$result = ((): number => {
    return a + b;
  })();
  if (!(kei$result === a + b)) {
    throw new KeiContractViolation({
      clause: "ensures",
      func: "addPositive",
      condition: "result == a + b",
      file: "math.kei",
      line: 6,
      col: 11,
    });
  }
  return kei$result;
}
//# sourceMappingURL=math.ts.map
