//! spec/ と examples/ をビルド時に埋め込む(ARCHITECTURE.md 不変条件 2)。
//!
//! 仕様・サンプルの内容を `include_str!`(絶対パス)で焼き込んだ
//! `OUT_DIR/embedded.rs` を生成する。`include_str!` がファイルを rustc の
//! 依存に登録するため、spec/ を編集して再ビルドすると埋め込み内容
//! ——ひいては `kei_spec` / `kei_examples` の応答——が必ず変わる。
//! ディレクトリへの `rerun-if-changed` でファイルの追加・削除も追従する。

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let root = manifest.join("..").join(".."); // crates/kei_mcp -> ワークスペースルート
    let spec_dir = root.join("spec");
    let examples_dir = root.join("examples");

    let spec_files = collect(&spec_dir, "md");
    let example_files = collect(&examples_dir, "kei");
    assert!(
        !spec_files.is_empty(),
        "no .md under {}",
        spec_dir.display()
    );
    assert!(
        !example_files.is_empty(),
        "no .kei under {}",
        examples_dir.display()
    );

    let mut code = String::from("// @generated by build.rs — do not edit.\n\n");
    emit_table(&mut code, "SPEC_FILES", &spec_dir, &spec_files);
    emit_table(&mut code, "EXAMPLE_FILES", &examples_dir, &example_files);

    let dest = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("embedded.rs");
    fs::write(&dest, code).expect("write embedded.rs");

    // ディレクトリ監視: ファイルの追加・削除で build.rs を再実行する。
    println!("cargo:rerun-if-changed={}", spec_dir.display());
    println!("cargo:rerun-if-changed={}", examples_dir.display());
    println!("cargo:rerun-if-changed=build.rs");
    // 個別ファイル監視: 内容変更で build.rs を再実行する(include_str! と二重の保険)。
    for f in spec_files.iter().chain(example_files.iter()) {
        println!("cargo:rerun-if-changed={}", f.display());
    }
}

/// `base` 直下を再帰探索し、拡張子 `ext` のファイルをパス昇順で返す。
fn collect(base: &Path, ext: &str) -> Vec<PathBuf> {
    let mut out = Vec::new();
    walk(base, ext, &mut out);
    out.sort();
    out
}

fn walk(dir: &Path, ext: &str, out: &mut Vec<PathBuf>) {
    let entries = match fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            walk(&path, ext, out);
        } else if path.extension().and_then(|e| e.to_str()) == Some(ext) {
            out.push(path);
        }
    }
}

/// `(相対パス, include_str!(絶対パス))` のテーブルを生成する。
fn emit_table(code: &mut String, name: &str, base: &Path, files: &[PathBuf]) {
    code.push_str(&format!("pub static {name}: &[(&str, &str)] = &[\n"));
    for f in files {
        let rel = f
            .strip_prefix(base)
            .expect("file under base")
            .to_string_lossy()
            .replace('\\', "/");
        let abs = f.to_string_lossy();
        // `{:?}` で Rust 文字列リテラルとして安全にエスケープして出力する。
        code.push_str(&format!("    ({rel:?}, include_str!({abs:?})),\n"));
    }
    code.push_str("];\n\n");
}
